#!/usr/bin/env bash
# Script that configures an Ubuntu server with specific IP requirements
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts